### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by davidfa94** [Arquisoft/Trivial_i2a#9]
I think more or less everything is uploaded about the documentation, but we talked about the user manual that should be written. In the last lab class we said Elias maybe could do it, do you or someone else have still time today to get an eye on it? (1 or 2 pages is only needed for getting it done)

**Comment by ilaia85** [comment]
Probably all of you don't kwow that due to my work it's very difficult for me to assist to lab practices. In fact i hardly am able to go to theory classes, so it's quite complicated for me tu be up to date.

I am now on a night shift (as the last two days) and it won't be possible for me to fulfill this task. It would be easier for me that this kind of decisions take place in this context (GitHub) and not in lab classes.

My apologies in advance for all of this. From now on i will try to be more involved in the work team.

**Comment by davidfa94** [comment]
I thought maybe someone said to you about the manual sorry, but yes from now on we should put the things written in the Wiki as the first time we divided it
